### PR TITLE
fix typo & add snapshots

### PR DESCRIPTION
**Pull request by IMPranshu**
## Description

In this PR I have added some snapshots for a better understanding of the installation process. I have fixed a typo that I found while going through the documentation.

## Type of change

Improvements to documentation (non-breaking change without functionality)

## Checklist

- [x] I have performed a self-review of my code

- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

- [x] Ship: this pull request can be automatically merged and does not require code review

### CODE REVIEW

**Review by marcelosousa — CHANGES_REQUESTED** [review]
@IMPranshu: many thanks for this contribution 🙌 ! 
Please propagate these changes to the next version of the docs as well. 
This means that we need add the same changes to the file: https://github.com/reviewpad/docs/blob/main/docs/getting-started/installation.md

**Comment by IMPranshu** [comment]
> @IMPranshu: many thanks for this contribution raised_hands ! Please propagate these changes to the next version of the docs as well. This means that we need add the same changes to the file: https://github.com/reviewpad/docs/blob/main/docs/getting-started/installation.md

Sure. On it

**Comment by IMPranshu** [comment]
> @IMPranshu: many thanks for this contribution raised_hands ! Please propagate these changes to the next version of the docs as well. This means that we need add the same changes to the file: https://github.com/reviewpad/docs/blob/main/docs/getting-started/installation.md

Can I ask why the process is like that?

On the website when I clicked `edit this page` it brought me to [that page](https://github.com/reviewpad/docs/blob/main/versioned_docs/version-3.3.1/getting-started/installation.md) on GitHub, so I went on by changing those files. 
image

**Comment by ferreiratiago** [comment]
That's a good point @IMPranshu When you click on `Edit` you're editing the current version in which you're on. By default the current version is the latest on the `versioned_docs` folder and not the actual `next` version (under `docs` folder). It's a bit confusing I know. We need to improve this process. Still learning about docusaurus.

**Review by ferreiratiago — APPROVED** [review]

**Pull request merged**
